import logger from 'debug'

/**
 * Middleware for catching errors thrown in routes
 * @param ctx
 * @returns {function}
 */
export default async function(ctx, next) {
    try {
        await next()
    } catch(error) {
        // Exceptions are generated by our app (ex: Wrong login)
        // So we don't need to log the whole stacktrace
        if (error.constructor.name === 'Exception') {
            logger('app:error')(error.message)
        } else {
            throw error
        }

        if (process.env.DEV) {
            return ctx.throw(400, error.toString())
        }
    }
}
